# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSCXQ-cm8fX0DZ6PynOylfC1b6eRd4y6
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import joblib
# import numpy as np
# 
# # Load saved model + preprocessing pipeline
# model = joblib.load("best_model.pkl")
# preprocessor = joblib.load("preprocessor.pkl")
# 
# st.set_page_config(page_title="AutoML Income Predictor", layout="wide")
# 
# st.title("💼 AI AutoML — Income Prediction System")
# st.write("Predict whether a person earns **more than 50K** using machine learning.")
# 
# # Sidebar
# st.sidebar.header("Navigation")
# page = st.sidebar.radio("Go to:", ["🔍 Predict Income", "📊 Model Info"])
# 
# # -----------------------------
# # PAGE 1 — PREDICTION
# # -----------------------------
# if page == "🔍 Predict Income":
# 
#     st.subheader("Enter User Details")
# 
#     age = st.number_input("Age", 18, 90, 30)
#     fnlwgt = st.number_input("FNLWGT", 10000, 1500000, 200000)
# 
#     education_num = st.slider("Education Level (1–16)", 1, 16, 12)
# 
#     capital_gain = st.number_input("Capital Gain", 0, 100000, 0)
#     capital_loss = st.number_input("Capital Loss", 0, 50000, 0)
# 
#     hours_per_week = st.slider("Hours per Week", 1, 80, 40)
# 
#     # Convert to DataFrame
#     input_data = pd.DataFrame([{
#         "age": age,
#         "fnlwgt": fnlwgt,
#         "education-num": education_num,
#         "capital-gain": capital_gain,
#         "capital-loss": capital_loss,
#         "hours-per-week": hours_per_week
#     }])
# 
#     if st.button("🔮 Predict Income"):
#         processed = preprocessor.transform(input_data)
#         prediction = model.predict(processed)[0]
# 
#         if prediction == ">50K":
#             st.success("💰 Prediction: **Income > 50K**")
#         else:
#             st.error("📉 Prediction: **Income <= 50K**")
# 
# # -----------------------------
# # PAGE 2 — MODEL INFO
# # -----------------------------
# if page == "📊 Model Info":
#     st.subheader("📊 Best Model Used: XGBoost")
# 
#     st.write("""
#     **This AutoML project trained the following models:**
#     - Logistic Regression
#     - Decision Tree
#     - Random Forest
#     - Gradient Boosting
#     - SVM
#     - KNN
#     - XGBoost (🔝 BEST)
#     """)
# 
#     st.info("XGBoost achieved the highest accuracy (0.848).")
# 
#     st.subheader("📌 Feature Importance (From XGBoost)")
# 
#     # Get feature names after preprocessing
#     feature_names = preprocessor.get_feature_names_out()
# 
#     # Get importances
#     try:
#         importances = model.feature_importances_
#         fi = pd.DataFrame({
#             "Feature": feature_names,
#             "Importance": importances
#         }).sort_values(by="Importance", ascending=False)
# 
#         st.dataframe(fi)
# 
#     except:
#         st.warning("Feature importance not available for this model.")
#